# Header
menu:
  主页: /
  所有文章: /archives
  每日糙点: /cao
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/ccjoe"
  # weibo: "#"
  # rss: "#"
  zhihu: "http://www.zhihu.com/people/chu0"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: false
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/ccjoe.ico

#你的头像url
avatar: /img/avatar.jpeg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: 74a9bd4718646fc83a6efcf6a34984b9
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  MDN: https://developer.mozilla.org/zh-CN/
  Github: http://www.github.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 理无常是，事无常非。 里面很多文章都是半完成式或在完善相关主题，仅作为作者整理思路， 读者见谅。